/* This file is generated by Ziggy. */
declare module 'ziggy-js' {
  interface RouteList {
    "sanctum.csrf-cookie": [],
    "abonnement.statut": [
        {
            "name": "reference",
            "required": true
        }
    ],
    "sync.push": [],
    "sync.pull": [],
    "sync.status": [],
    "home": [],
    "entreprise.create": [],
    "entreprise.store": [],
    "upgrade": [],
    "abonnement.index": [],
    "abonnement.payer": [],
    "dashboard": [],
    "caisse.index": [],
    "caisse.initial": [],
    "ressources-humaines.index": [],
    "profil.index": [],
    "tiers.index": [],
    "succursales.store": [],
    "succursales.index": [],
    "succursales.show": [
        {
            "name": "succursale",
            "required": true,
            "binding": "id"
        }
    ],
    "succursales.exit": [],
    "succursales.update": [
        {
            "name": "succursale",
            "required": true,
            "binding": "id"
        }
    ],
    "succursales.destroy": [
        {
            "name": "succursale",
            "required": true,
            "binding": "id"
        }
    ],
    "transferts.index": [],
    "transferts.caisse": [],
    "transferts.stock": [],
    "transferts.approve": [
        {
            "name": "transfert",
            "required": true,
            "binding": "id"
        }
    ],
    "transferts.reject": [
        {
            "name": "transfert",
            "required": true,
            "binding": "id"
        }
    ],
    "employes.update": [
        {
            "name": "employe",
            "required": true,
            "binding": "id"
        }
    ],
    "employes.destroy": [
        {
            "name": "employe",
            "required": true,
            "binding": "id"
        }
    ],
    "employes.index": [],
    "employes.create": [],
    "employes.store": [],
    "employes.edit": [
        {
            "name": "employe",
            "required": true
        }
    ],
    "produits.update": [
        {
            "name": "produit",
            "required": true,
            "binding": "id"
        }
    ],
    "produits.destroy": [
        {
            "name": "produit",
            "required": true,
            "binding": "id"
        }
    ],
    "produits.update.fallback": [],
    "produits.destroy.fallback": [],
    "produits.index": [],
    "produits.create": [],
    "produits.edit": [
        {
            "name": "produit",
            "required": true
        }
    ],
    "produits.store": [],
    "clients.update": [
        {
            "name": "client",
            "required": true,
            "binding": "id"
        }
    ],
    "clients.destroy": [
        {
            "name": "client",
            "required": true,
            "binding": "id"
        }
    ],
    "clients.index": [],
    "clients.create": [],
    "clients.edit": [
        {
            "name": "client",
            "required": true
        }
    ],
    "clients.store": [],
    "fournisseurs.update": [
        {
            "name": "fournisseur",
            "required": true,
            "binding": "id"
        }
    ],
    "fournisseurs.destroy": [
        {
            "name": "fournisseur",
            "required": true,
            "binding": "id"
        }
    ],
    "fournisseurs.index": [],
    "fournisseurs.create": [],
    "fournisseurs.edit": [
        {
            "name": "fournisseur",
            "required": true
        }
    ],
    "fournisseurs.store": [],
    "mouvement-stocks.generer-facture": [],
    "mouvement-stocks.generer-bon-entree": [],
    "mouvement-stocks.index": [],
    "mouvement-stocks.create": [],
    "mouvement-stocks.store": [],
    "mouvement-stocks.show": [
        {
            "name": "mouvement_stock",
            "required": true
        }
    ],
    "mouvement-stocks.edit": [
        {
            "name": "mouvement_stock",
            "required": true
        }
    ],
    "mouvement-stocks.update": [
        {
            "name": "mouvement_stock",
            "required": true
        }
    ],
    "mouvement-stocks.destroy": [
        {
            "name": "mouvement_stock",
            "required": true
        }
    ],
    "journals.index": [],
    "journals.store": [],
    "fiches.index": [],
    "fiches.store": [],
    "fiches.update": [
        {
            "name": "fich",
            "required": true
        }
    ],
    "fiches.destroy": [
        {
            "name": "fich",
            "required": true
        }
    ],
    "fiches.confirmer": [
        {
            "name": "fiche",
            "required": true,
            "binding": "id"
        }
    ],
    "fiches.confirmer.post": [
        {
            "name": "fiche",
            "required": true,
            "binding": "id"
        }
    ],
    "fiches.confirmer.fallback": [],
    "users.index": [],
    "users.store": [],
    "users.update": [
        {
            "name": "user",
            "required": true,
            "binding": "id"
        }
    ],
    "users.destroy": [
        {
            "name": "user",
            "required": true,
            "binding": "id"
        }
    ],
    "users.access": [
        {
            "name": "user",
            "required": true,
            "binding": "id"
        }
    ],
    "creances-dettes.index": [],
    "creances-dettes.clients.payer": [
        {
            "name": "client",
            "required": true,
            "binding": "id"
        }
    ],
    "creances-dettes.fournisseurs.payer": [
        {
            "name": "fournisseur",
            "required": true,
            "binding": "id"
        }
    ],
    "creances-dettes.clients.detail": [
        {
            "name": "client",
            "required": true,
            "binding": "id"
        }
    ],
    "creances-dettes.fournisseurs.detail": [
        {
            "name": "fournisseur",
            "required": true,
            "binding": "id"
        }
    ],
    "creances-dettes.clients.pdf": [
        {
            "name": "client",
            "required": true,
            "binding": "id"
        }
    ],
    "creances-dettes.fournisseurs.pdf": [
        {
            "name": "fournisseur",
            "required": true,
            "binding": "id"
        }
    ],
    "rapport.log": [],
    "parametres.index": [],
    "parametres.store": [],
    "parametres.update": [
        {
            "name": "parametre",
            "required": true,
            "binding": "id"
        }
    ],
    "factures.index": [],
    "factures.create": [],
    "factures.store": [],
    "factures.show": [
        {
            "name": "facture",
            "required": true,
            "binding": "id"
        }
    ],
    "factures.edit": [
        {
            "name": "facture",
            "required": true
        }
    ],
    "factures.update": [
        {
            "name": "facture",
            "required": true
        }
    ],
    "factures.destroy": [
        {
            "name": "facture",
            "required": true
        }
    ],
    "archives.factures": [],
    "archives.index": [],
    "archives.factures.pdf": [
        {
            "name": "date",
            "required": true
        }
    ],
    "archives.download": [
        {
            "name": "type",
            "required": true
        },
        {
            "name": "date",
            "required": true
        }
    ],
    "archives.pdf": [
        {
            "name": "type",
            "required": true
        },
        {
            "name": "date",
            "required": true
        }
    ],
    "archives.month": [
        {
            "name": "type",
            "required": true
        },
        {
            "name": "year",
            "required": true
        },
        {
            "name": "month",
            "required": true
        }
    ],
    "archives.day": [
        {
            "name": "type",
            "required": true
        },
        {
            "name": "date",
            "required": true
        }
    ],
    "historique.mouvements-stock": [],
    "historique.journaux": [],
    "archives.mouvements-stock": [],
    "archives.mouvements-stock.download": [
        {
            "name": "date",
            "required": true
        }
    ],
    "archives.mouvements-stock.preview": [
        {
            "name": "date",
            "required": true
        }
    ],
    "archives.journaux": [],
    "archives.journaux.download": [
        {
            "name": "date",
            "required": true
        }
    ],
    "archives.journaux.preview": [
        {
            "name": "date",
            "required": true
        }
    ],
    "rapport.index": [],
    "admin.plans": [],
    "admin.plans.activate": [
        {
            "name": "entreprise",
            "required": true,
            "binding": "id"
        }
    ],
    "admin.plans.downgrade": [
        {
            "name": "entreprise",
            "required": true,
            "binding": "id"
        }
    ],
    "owner.login": [],
    "owner.login.post": [],
    "owner.logout": [],
    "owner.dashboard": [],
    "owner.plans.activate": [
        {
            "name": "entreprise",
            "required": true,
            "binding": "id"
        }
    ],
    "owner.plans.downgrade": [
        {
            "name": "entreprise",
            "required": true,
            "binding": "id"
        }
    ],
    "register": [],
    "login": [],
    "password.request": [],
    "password.email": [],
    "password.reset": [
        {
            "name": "token",
            "required": true
        }
    ],
    "password.store": [],
    "verification.notice": [],
    "verification.verify": [
        {
            "name": "id",
            "required": true
        },
        {
            "name": "hash",
            "required": true
        }
    ],
    "verification.send": [],
    "password.confirm": [],
    "password.update.auth": [],
    "logout": [],
    "profile.edit": [],
    "profile.update": [],
    "profile.destroy": [],
    "password.edit": [],
    "password.update": [],
    "appearance": [],
    "storage.local": [
        {
            "name": "path",
            "required": true
        }
    ]
}
}
export {};
